#+TITLE:  Task 5.3 -- Org
#+AUTHOR: Dirk Oliver Theis, University of Tartu, Estonia
#+EMAIL:  dotheis@ut.ee
#+DATE:   Thu Nov 23 12:08:33 EET 2023

#+STARTUP: show3levels
#+SEQ_TODO: TODO DOING CONT In-Tst ARGH ↘️ | ToTST DONE

You're here: [[¤CONTINUE HERE][¤CONTINUE HERE]] <<¤CONTINUE HERE>>

* Task Description

   _Task 5.3: Software stack_

   (Partners involved: UTartu*, Wigner RCP, Qruise, TNO, FZJ; Duration: M1-M42)

   Once the QC is fully calibrated, we require an optimizing compiler to best match users’ circuits to each
   hardware’s specific capabilities.  In addition, a Quantum OS is required, allowing lab members and trusted
   collaborators to submit circuits for execution (a.k.a. private cloud), and including everything needed for
   ongoing operations: a scheduler, recalibration and status monitoring.

   Creation of an *optimizing compiler* will be led by UTartu and be comprised of two steps.  In *Phase 1*
   (deliverable D5.3) WP4[sic! should be 5] shall implement an optimizing compiler which would allow arbitrary
   quantum circuits to be executed on OpenSuperQPlus100 hardware.  Optimized mapping of circuit layout and
   gate-set.  In *Phase 2*, the Phase 1 compiler shall be extended to include /dynamic adaptation to newly
   calibrated gates and gate error rates/ as well as support for /integration of classical logic/ in the quantum
   circuit for error correction implementation.

   To allow efficient work by the various project partners, we must allow for shared usage of the QCs.  In other
   words – we must provide for private *cloud access*.  This will comprise of a means of sending circuits to be
   evaluated, a circuit *queue*, and a mechanism to return results (milestone MS17).  Further, to allow certain
   maintenance operations of the QCs and to prevent interactive algorithms from going back to the end of the queue
   in each iteration, priorities shall be built into the queuing mechanism.

   It is imperative that QPUs keep operating at the lowest error rates.  For that purpose, *recalibration* shall be
   implemented, with the goal of minimizing QC downtime and maximizing fidelities throughout.  Finally, basic
   *monitoring* capabilities will be provided (deliverable D5.7), to allow QC operators to view system health and
   performance.


* Task Outline: Milestones, Deliverables, etc

** Components

    * Optimizing Compiler (UTartu)
      + Phase 1
      + Phase 2

    * Quantum OS (Qruise)
      + Cloud access
        - Scheduler
      + Recalibration
      + Monitoring

** Relies on

    | Key | Name                                                                      | Respo. | Start |  Dead |
    |-----+---------------------------------------------------------------------------+--------+-------+-------|
    | M7  | User reqs, system specs & breakdown based on plans, interface defs agreed | Orange | 24-01 | 24-02 |
    | M9  | Interface [from WP4] to WP5 operational                                   | Orange | 24-04 | 24-05 |
    | M3  | Low-level interface phase 1 definition                                    | Qruise | 23-07 | 23-08 |
    | M17 | Low-level interface phase 2 definition                                    | Qruise | 25-01 | 25-02 |

** Output

    | Key  | Name                                      |      Start |       Dead |
    |------+-------------------------------------------+------------+------------|
    | D5.3 | Optimizing Compiler v1                    | 2025-01-01 | 2025-02-28 |
    | D5.7 | Quantum OS — Monitoring and recalibration | 2026-07-01 | 2026-08-31 |


* Task-Leader Reports
** TLR Nov 2023: Task 5.3 /Software Stack/

*** Other project partners participating in the task: UTartu*, Wigner RCP, Qruise, TNO, FZJ

     Please describe what has been carried out and achieved in the task during the respective period and in line
     with the WP descriptions included in Annex 1 - Description of the action (part A) to the GA.  Include
     contributions from other project members participating in the task by mentioning their abbreviation.  Keep it
     short and concise (preferably up to 1 - 1 ½ page) but do not use bullet points.

*** 1.1.1 Deviations from Annex I., the consequences and the proposed corrective actions

None.

*** 1.1.2 Activities / critical objectives or deliverables

The development of Phase 1 of the optimizing compiler has started by assigning: to Wigner RCP the sub-task of
contributing improved gate factorization; to UTartu the 


*** 1.1.3 Implementation risks and mitigation actions

N/A

(Risk № 5 "No hardware available for testing of software stack" does not apply as testing hasn't started yet.)

*** 1.1.4 Unforeseen Risks



* Footnotes
# Local Variables:
# fill-column: 115
# End:
