#+TITLE:  OSQ+100 Task 7.3 "Verification & Validation" -- Project Management
#+AUTHOR: Dirk Oliver Theis, University of Tartu, Estonia
#+EMAIL:  dotheis.UTartu@gmail.com
#+DATE:   Mon Nov 27 16:42:19 EET 2023

#+STARTUP: show3levels
#+SEQ_TODO: TODO DOING CONT In-Tst ARGH ↘️ | ToTST DONE

* Task Description

   From the Grant Agreement

   #+BEGIN_QUOTE
      _Task 7.3: Verification and Validation_

      (Partners involved: UTartu*, UPV/EHU, CHALMERS, FZJ, Qruise, Duration: month 1-42)

      The levels of the enabling software stack communicate via interfaces.  This task is concerned with (a)
      *validating* that the top-level interfaces meet the requirements for application quantum software, including
      quantum gates/circuits with fault tolerance, and (b) *verifying* that the implementations match the
      specifications.  CHALMERS and UPV/EHU will do (a) as /part of their development of application software/ as
      part of the test suite in Tasks 7.1 and 7.2., scheduling it to match the timelines for those tasks.  The
      results of Task 7.3 will be applied at *test nodes* in Task 1.2.  FZJ, Qruise, and UTartu will /develop
      methodology/ for verifying the correctness of the implementations (D7.3 in M42; candidate methods will be
      identified by M6, implementation and validation of the software will begin before M24).  For levels of the
      software stack that link classical input to classical output (e.g., optimization phases in the quantum
      compiler), /quantum simulation/ will be deployed (see Task 7.5).  For the levels of the software stack that
      directly communicate with the control hardware, process tomography and randomized benchmarking, *et cetera*,
      will be used.  CHALMERS will assist with state and process tomography.
   #+END_QUOTE


* Task Outline: Milestones, Deliverables, etc
** Components

    * Validation (UPV/EHU, CHALMERS)
    * Verification (FZJ, Qruise, UTartu)

** Relies on

    | Key | Name                                                                      | Respo. | Start |  Dead |
    |-----+---------------------------------------------------------------------------+--------+-------+-------|
    | M7  | User reqs, system specs & breakdown based on plans, interface defs agreed | Orange | 24-01 | 24-02 |

** Output

    | Key  | Name                                                           |      Start |       Dead |
    |------+----------------------------------------------------------------+------------+------------|
    | O7.3 | Develop protocols, software for verif.+valid. of full QC stack |        n/a |        n/a |
    | M24  | Consensus of interface specifications for verification         | 2026-01-01 | 2026-02-28 |
    | D7.3 | Methodology for verifying the quantum stack                    | 2026-07-01 | 2026-08-31 |

** Contributing partners

      | Partner    | Total PMs |
      |            | in WP7    |
      |------------+-----------|
      | _UTartu_   | 36        |
      | FZJ        | 70        |
      | CHALMERS   | 54        |
      | UPV/EHU    | 38        |
      | Qruise     | 0         |



* Task-Leader Reports
** TLR Nov 2023: Task 7.3 /Verification and Validation/

    * Task leader:
      + UTartu
    * Other project partners participating in the task:
      + FZJ
      + Qruise
      + UPV/EHU
      + CHALMERS

*** Deviations from Annex I., the consequences and the proposed corrective actions

     None.

*** Activities / critical objectives or deliverables

     As indicated in the task description in the GA and then discussed in the consortium meeting in July in Bilbao,
     the work for the valification will be carried out by UPV/EHU and CHALMERS, as, in the context of developing
     applications to run on the stack, they are in the best position to validate the interfaces.

     The next milestone concerning Verification is M24 /M24 Consensus of OpenSuperQPlus100 interface specifications
     for verification/ in Jan-Feb, 2026.  In moving towards that milestone, Task 7.3 implementers are in
     communication with the implementers of Task 8.3 "Standards and interfaces".

     The process of identifying candidate methods for verification has commenced, and UTartu hired
     researcher/specialist to work part-time for identifying and implementing verification methods.  One of the
     senior researchers at UTartu also works part-time on verification methodology as of Oct 1.

*** Implementation risks and mitigation actions

     N/A

*** Unforeseen Risks

     No unforeseen risks are foreseen.

* End Of File
# Local Variables:
# fill-column: 115
# End:
